name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Check environment variables
      run: |
        export
        which ndk-build

