name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build for Android
      run: |
        export
        (cd build; bash make_android_lua53_arm64.sh)
